/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Toolkit;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.Calendar;
import java.util.TimeZone;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author José Luan Silva do Nascimento, 20141064010220
 */
public class Visual extends javax.swing.JFrame {

    /**
     * Creates new form Visual
     */

    public Visual() {
        initComponents();
        this.setLocationRelativeTo(null);
        totalhoras[0]=0;
        totalhoras[1]=0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btentrada = new javax.swing.JButton();
        btsaida3 = new javax.swing.JButton();
        btcadastrar = new javax.swing.JButton();
        tfnome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txadados = new javax.swing.JTextArea();
        btsalvar = new javax.swing.JButton();
        btabrir = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel6 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jlhoras = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btcalcular = new javax.swing.JButton();
        jllog = new javax.swing.JLabel();
        txsaida = new javax.swing.JTextField();
        txentrada = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jltotalhoras = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(Toolkit.getDefaultToolkit().getImage(this.getClass().getResource("logoscgrande.png")) );
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btentrada.setBackground(new java.awt.Color(153, 0, 19));
        btentrada.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btentrada.setForeground(new java.awt.Color(241, 255, 249));
        btentrada.setText("Hora atual entrada");
        btentrada.setBorder(null);
        btentrada.setBorderPainted(false);
        btentrada.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btentradaActionPerformed(evt);
            }
        });

        btsaida3.setBackground(new java.awt.Color(153, 0, 19));
        btsaida3.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btsaida3.setForeground(new java.awt.Color(241, 255, 249));
        btsaida3.setText("Hora atual saída");
        btsaida3.setBorder(null);
        btsaida3.setBorderPainted(false);
        btsaida3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btsaida3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsaida3ActionPerformed(evt);
            }
        });

        btcadastrar.setBackground(new java.awt.Color(0, 79, 63));
        btcadastrar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btcadastrar.setForeground(new java.awt.Color(241, 255, 249));
        btcadastrar.setText("Cadastrar");
        btcadastrar.setBorder(null);
        btcadastrar.setBorderPainted(false);
        btcadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btcadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcadastrarActionPerformed(evt);
            }
        });

        tfnome.setFont(new java.awt.Font("Corbel", 1, 14)); // NOI18N
        tfnome.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(81, 185, 171), 1, true));
        tfnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfnomeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(12, 142, 125));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Nome");
        jLabel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Corbel", 1, 30)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(6, 116, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("SISTEMA DE CONTROLE DE HORÁRIOS DE FUNCIONÁRIOS");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/logoscgrande.png"))); // NOI18N

        txadados.setColumns(20);
        txadados.setFont(new java.awt.Font("Corbel", 1, 18)); // NOI18N
        txadados.setLineWrap(true);
        txadados.setRows(5);
        txadados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(81, 185, 171)));
        jScrollPane1.setViewportView(txadados);

        btsalvar.setBackground(new java.awt.Color(153, 0, 19));
        btsalvar.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btsalvar.setForeground(new java.awt.Color(241, 255, 249));
        btsalvar.setText("Salvar");
        btsalvar.setBorder(null);
        btsalvar.setBorderPainted(false);
        btsalvar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btsalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsalvarActionPerformed(evt);
            }
        });

        btabrir.setBackground(new java.awt.Color(0, 79, 63));
        btabrir.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btabrir.setForeground(new java.awt.Color(241, 255, 249));
        btabrir.setText("Abrir");
        btabrir.setBorder(null);
        btabrir.setBorderPainted(false);
        btabrir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btabrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btabrirActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(12, 142, 125));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Hora entrada:");
        jLabel4.setToolTipText("");

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(12, 142, 125));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hora saída:");
        jLabel5.setToolTipText("");

        jSeparator1.setForeground(new java.awt.Color(6, 116, 102));
        jSeparator1.setAlignmentX(1.0F);
        jSeparator1.setAlignmentY(1.0F);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(12, 142, 125));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Histórico:");
        jLabel6.setToolTipText("");

        jSeparator2.setForeground(new java.awt.Color(6, 116, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jlhoras.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jlhoras.setForeground(new java.awt.Color(12, 142, 125));
        jlhoras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlhoras.setToolTipText("");
        jlhoras.setEnabled(false);

        jLabel9.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(12, 142, 125));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Horas em serviço:");
        jLabel9.setToolTipText("");

        btcalcular.setBackground(new java.awt.Color(153, 0, 19));
        btcalcular.setFont(new java.awt.Font("Comic Sans MS", 1, 12)); // NOI18N
        btcalcular.setForeground(new java.awt.Color(241, 255, 249));
        btcalcular.setText("Calcular");
        btcalcular.setBorder(null);
        btcalcular.setBorderPainted(false);
        btcalcular.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btcalcularActionPerformed(evt);
            }
        });

        jllog.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jllog.setForeground(new java.awt.Color(153, 0, 19));
        jllog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jllog.setText("Faça o login de um funcionário!");
        jllog.setToolTipText("");

        txsaida.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txsaida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txsaidaActionPerformed(evt);
            }
        });

        txentrada.setFont(new java.awt.Font("Comic Sans MS", 1, 14)); // NOI18N
        txentrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txentradaActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(12, 142, 125));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Total horas:");
        jLabel8.setToolTipText("");

        jltotalhoras.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jltotalhoras.setForeground(new java.awt.Color(12, 142, 125));
        jltotalhoras.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jltotalhoras.setToolTipText("");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 910, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jlhoras, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txsaida)
                                    .addComponent(txentrada, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btentrada, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                    .addComponent(btcalcular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btsaida3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(btsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btabrir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jllog, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jltotalhoras, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(13, 13, 13)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 813, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(13, Short.MAX_VALUE)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfnome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jllog))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(btentrada, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txentrada, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txsaida, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btsaida3, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(jlhoras, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(btcalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9)))
                                .addGap(11, 11, 11)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btsalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btcadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btabrir, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(1, 1, 1))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jltotalhoras, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator2))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private static final Calendar calendarioatual = Calendar.getInstance(TimeZone.getTimeZone("Brazil/East"));
    private static final int[] saida = new int[2];
    private static final int[] entrada = new int[2];
    private static final int[] totalhoras = new int[2];
    private static final int dia = calendarioatual.get(Calendar.DAY_OF_MONTH);
    private static String nomearquivo = "";
    private static String nome = "";
    private static String mensagem = "";
    private boolean log = false;
    private static final int[] horas = new int[2]; 
    
    private void btentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btentradaActionPerformed
        if (log) {
            Calendar calendariolocal = Calendar.getInstance(TimeZone.getTimeZone("Brazil/East"));
            String entradatexto = "";
            entradatexto += calendariolocal.get(Calendar.HOUR_OF_DAY)+":";
            entradatexto += calendariolocal.get(Calendar.MINUTE);
            
            txentrada.setText(entradatexto);
        }
    }//GEN-LAST:event_btentradaActionPerformed

    private void btsaida3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsaida3ActionPerformed
        if (log) {
            Calendar calendariolocal = Calendar.getInstance(TimeZone.getTimeZone("Brazil/East"));
            String entradatexto = "";
            entradatexto += calendariolocal.get(Calendar.HOUR_OF_DAY)+":";
            entradatexto += calendariolocal.get(Calendar.MINUTE);
            
            txsaida.setText(entradatexto);
        }
  
    }//GEN-LAST:event_btsaida3ActionPerformed

    private void btcadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcadastrarActionPerformed
        save(tfnome.getText()+",null,null#");
        JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!!!","___Salvo___", WIDTH);
        log = true;
        btsalvar.setBackground(new java.awt.Color(0,79,63));
        btentrada.setBackground(new java.awt.Color(0,79,63));
        btsaida3.setBackground(new java.awt.Color(0,79,63));
        btcalcular.setBackground(new java.awt.Color(0,79,63));
        jllog.setText("");
    }//GEN-LAST:event_btcadastrarActionPerformed

    private void tfnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfnomeActionPerformed

    private void btsalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsalvarActionPerformed
        if (log) {
            try {
                String[] entradatx = new String[2];
                String[] saidatx = new String[2];

                entradatx[0] = txentrada.getText().split(":")[0];
                entradatx[1] = txentrada.getText().split(":")[1];

                saidatx[0] = txsaida.getText().split(":")[0];
                saidatx[1] = txsaida.getText().split(":")[1];

                if (((Integer.parseInt(saidatx[0]) <= 23 && Integer.parseInt(saidatx[0]) >= 0) && (Integer.parseInt(saidatx[1]) < 60 && Integer.parseInt(saidatx[1]) >= 0)) && ((Integer.parseInt(entradatx[1]) <= 23 && Integer.parseInt(entradatx[1]) >= 0))&&(Integer.parseInt(entradatx[0]) < 60 && Integer.parseInt(entradatx[0]) >= 0)) {
                    
                    
                    if ((Integer.parseInt(saidatx[1]) == Integer.parseInt(entradatx[1]))){ 
                        horas[1] = 0;                
                        
                        
                        if ((Integer.parseInt(saidatx[0]) > Integer.parseInt(entradatx[0]))) {
                        
                            horas[0] = Integer.parseInt(saidatx[0]) -  Integer.parseInt(entradatx[0]);
                        
                        }else if((Integer.parseInt(saidatx[0]) < Integer.parseInt(entradatx[0]))){

                            horas[0] = Integer.parseInt(entradatx[0]) - Integer.parseInt(saidatx[0]);

                        }
                        
                    }else if ((Integer.parseInt(saidatx[0]) == Integer.parseInt(entradatx[0]))){
                        horas[0] = 0;
                        
                        
                        if ((Integer.parseInt(saidatx[1]) > Integer.parseInt(entradatx[1]))) {
                        
                            horas[1] = Integer.parseInt(saidatx[1]) -  Integer.parseInt(entradatx[1]);
                        
                        }else if((Integer.parseInt(saidatx[1]) < Integer.parseInt(entradatx[1]))){

                            horas[1] = Integer.parseInt(entradatx[1]) - Integer.parseInt(saidatx[1]);

                        }
                        
                        
                    }
                    
                    
                    if ((Integer.parseInt(saidatx[0]) > Integer.parseInt(entradatx[0])) && (Integer.parseInt(saidatx[1]) > Integer.parseInt(entradatx[1]))) {
                        
                        horas[0] = Integer.parseInt(saidatx[0]) -  Integer.parseInt(entradatx[0]);
                        horas[1] = Integer.parseInt(saidatx[1]) - Integer.parseInt(entradatx[1]);
                        
                    }else if((Integer.parseInt(saidatx[0]) > Integer.parseInt(entradatx[0])) && (Integer.parseInt(saidatx[1]) < Integer.parseInt(entradatx[1]))){
                        
                        horas[0] = Integer.parseInt(saidatx[0]) - Integer.parseInt(entradatx[0]);
                        horas[1] = Integer.parseInt(entradatx[1]) - Integer.parseInt(saidatx[1]);
                        
                    }
                     
                    
                    else if((Integer.parseInt(saidatx[0]) < Integer.parseInt(entradatx[0])) && (Integer.parseInt(saidatx[1]) < Integer.parseInt(entradatx[1]))){
                        
                        horas[0] = Integer.parseInt(entradatx[0]) - Integer.parseInt(saidatx[0]);
                        horas[1] = Integer.parseInt(entradatx[1]) - Integer.parseInt(saidatx[1]);
                        
                    }else if((Integer.parseInt(saidatx[0]) < Integer.parseInt(entradatx[0])) && (Integer.parseInt(saidatx[1]) > Integer.parseInt(entradatx[1]))){
                        
                        horas[0] = Integer.parseInt(entradatx[0]) - Integer.parseInt(saidatx[0]);
                        horas[1] = Integer.parseInt(saidatx[1]) - Integer.parseInt(entradatx[1]);
                        
                    }
                    

                        System.out.println("o");
                        
                        String novamensagem = nome+","+dia+","+horas[0]+":"+horas[1]+"#";
                        
                        totalhoras[0] += horas[0];
                        totalhoras[1] += horas[1];
                        
                        totalhoras[0] += totalhoras[1]/60;
                        totalhoras[1] = totalhoras[1] % 60;
                        
                        //salvando o texto do JTextArea da aba selecionada
                        try (PrintWriter arq = new PrintWriter(nomearquivo)) {
                            //salvando o texto no arquivo8
                            arq.println(mensagem+novamensagem);
                            //mensagem de confirmacao 
                            JOptionPane.showMessageDialog(rootPane, "Salvo com sucesso!!!","___Salvo___", WIDTH);
                            arq.close();
                            txadados.setText(txadados.getText()+"Dia:  "+dia+"    Horas:  "+horas[0]+":"+horas[1]+"h\n");

                        }catch (RuntimeException ex) { 
                            //mensagem de execao
                            JOptionPane.showMessageDialog(rootPane, "Tem algo erado com suas horas\n"
                                    + "corrija e tente novamente :) \n"
                                    + "Exeção "+ex.getMessage(),"___Exeção___", WIDTH);
                        } catch (FileNotFoundException ex) {
                        Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
                    }
               }
                    
                

                jltotalhoras.setText(totalhoras[0]+":"+totalhoras[1]);
            } catch (RuntimeException e) {
                JOptionPane.showInternalMessageDialog(this, "Acho que voçê digitou errado o formato de hora\n"
                        + "Digite h:mm, hora:minutos e tente novamente!\n"
                        + "Exceção"+e.getMessage(),"__Exceção__", dia);
            }
            
        }
    }//GEN-LAST:event_btsalvarActionPerformed

    private void btabrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btabrirActionPerformed
        try{
            
            String conteudo = open();
            mensagem = conteudo;
            String dados = "";
            for (String temporario : conteudo.split("#")) {
                String[] conte = temporario.split(",");
                nome = conte[0];
                tfnome.setText(nome);
                if (!conte[1].equals("null") && !conte[2].equals("null")) {
                    dados += "Dia:  "+conte[1]+":    Horas:  "+conte[2]+"h\n";
                    
                    totalhoras[0] += Integer.parseInt(conte[2].split(":")[0]); 
                    totalhoras[1] += Integer.parseInt(conte[2].split(":")[1]); 
                    
                }
            }
            jllog.setText("");
            txadados.setText(dados);
            log = true;
            btsalvar.setBackground(new java.awt.Color(0,79,63));
            btentrada.setBackground(new java.awt.Color(0,79,63));
            btsaida3.setBackground(new java.awt.Color(0,79,63));
            btcalcular.setBackground(new java.awt.Color(0,79,63));
            
            totalhoras[0] += (int) totalhoras[1]/60;
            totalhoras[1] = (int) totalhoras[1] % 60;
            
            jltotalhoras.setText(totalhoras[0]+":"+totalhoras[1]);
        }catch(Exception e){
            System.out.println("Ops. deu pau ! Ocorreu a exceção: "+e.getMessage());
        }
    }//GEN-LAST:event_btabrirActionPerformed

    private void btcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btcalcularActionPerformed
        if (log) {
            String[] entradatx = new String[2];
            String[] saidatx = new String[2];
            
            
            
            try{
                entradatx[0] = txentrada.getText().split(":")[0];
                entradatx[1] = txentrada.getText().split(":")[1];

                saidatx[0] = txsaida.getText().split(":")[0];
                saidatx[1] = txsaida.getText().split(":")[1];
                
                
                
                if (((Integer.parseInt(saidatx[0]) <= 23 && Integer.parseInt(saidatx[0]) >= 0) && (Integer.parseInt(saidatx[1]) < 60 && Integer.parseInt(saidatx[1]) >= 0)) && ((Integer.parseInt(entradatx[1]) < 60 && Integer.parseInt(entradatx[1]) >= 0))&&(Integer.parseInt(entradatx[0]) <= 23 && Integer.parseInt(entradatx[0]) >= 0)) {
                   
                    if ((Integer.parseInt(saidatx[1]) == Integer.parseInt(entradatx[1]))){ 
                        horas[1] = 0;                
                        
                        
                        if ((Integer.parseInt(saidatx[0]) > Integer.parseInt(entradatx[0]))) {
                        
                            horas[0] = Integer.parseInt(saidatx[0]) -  Integer.parseInt(entradatx[0]);
                        
                        }else if((Integer.parseInt(saidatx[0]) < Integer.parseInt(entradatx[0]))){

                            horas[0] = Integer.parseInt(entradatx[0]) - Integer.parseInt(saidatx[0]);

                        }
                        
                    }else if ((Integer.parseInt(saidatx[0]) == Integer.parseInt(entradatx[0]))){
                        horas[0] = 0;
                        
                        
                        if ((Integer.parseInt(saidatx[1]) > Integer.parseInt(entradatx[1]))) {
                        
                            horas[1] = Integer.parseInt(saidatx[1]) -  Integer.parseInt(entradatx[1]);
                        
                        }else if((Integer.parseInt(saidatx[1]) < Integer.parseInt(entradatx[1]))){

                            horas[1] = Integer.parseInt(entradatx[1]) - Integer.parseInt(saidatx[1]);

                        }
                        
                        
                    }
                    
                    
                    if ((Integer.parseInt(saidatx[0]) > Integer.parseInt(entradatx[0])) && (Integer.parseInt(saidatx[1]) > Integer.parseInt(entradatx[1]))) {
                        
                        horas[0] = Integer.parseInt(saidatx[0]) -  Integer.parseInt(entradatx[0]);
                        horas[1] = Integer.parseInt(saidatx[1]) - Integer.parseInt(entradatx[1]);
                        
                    }else if((Integer.parseInt(saidatx[0]) > Integer.parseInt(entradatx[0])) && (Integer.parseInt(saidatx[1]) < Integer.parseInt(entradatx[1]))){
                        
                        horas[0] = Integer.parseInt(saidatx[0]) - Integer.parseInt(entradatx[0]);
                        horas[1] = Integer.parseInt(entradatx[1]) - Integer.parseInt(saidatx[1]);
                        
                    }
                     
                    
                    else if((Integer.parseInt(saidatx[0]) < Integer.parseInt(entradatx[0])) && (Integer.parseInt(saidatx[1]) < Integer.parseInt(entradatx[1]))){
                        
                        horas[0] = Integer.parseInt(entradatx[0]) - Integer.parseInt(saidatx[0]);
                        horas[1] = Integer.parseInt(entradatx[1]) - Integer.parseInt(saidatx[1]);
                        
                    }else if((Integer.parseInt(saidatx[0]) < Integer.parseInt(entradatx[0])) && (Integer.parseInt(saidatx[1]) > Integer.parseInt(entradatx[1]))){
                        
                        horas[0] = Integer.parseInt(entradatx[0]) - Integer.parseInt(saidatx[0]);
                        horas[1] = Integer.parseInt(saidatx[1]) - Integer.parseInt(entradatx[1]);
                        
                    }

                    jlhoras.setText(horas[0]+":"+horas[1]);

                    
                }
            
            }catch(RuntimeException e){
                JOptionPane.showInternalMessageDialog(this, "Acho que voçê digitou errado o formato de hora\n"
                        + "Digite h:mm, hora:minutos e tente novamente!\n"
                        + "Exceção"+e.getMessage(),"__Exceção__", dia);
            }
            
        }
    }//GEN-LAST:event_btcalcularActionPerformed

    private void txsaidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txsaidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txsaidaActionPerformed

    private void txentradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txentradaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txentradaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Visual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Visual().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btabrir;
    private javax.swing.JButton btcadastrar;
    private javax.swing.JButton btcalcular;
    private javax.swing.JButton btentrada;
    private javax.swing.JButton btsaida3;
    private javax.swing.JButton btsalvar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel jlhoras;
    private javax.swing.JLabel jllog;
    private javax.swing.JLabel jltotalhoras;
    private javax.swing.JTextField tfnome;
    private javax.swing.JTextArea txadados;
    private javax.swing.JTextField txentrada;
    private javax.swing.JTextField txsaida;
    // End of variables declaration//GEN-END:variables

    public static String open(){
        JFileChooser abrir = new JFileChooser();
        String texto = "";
        String src;
        abrir.setDialogTitle("Abrir");
        abrir.setFileFilter(new javax.swing.filechooser.FileFilter() {

            @Override
            public boolean accept(File f) {
                return f.getName().endsWith(".funcionario") || f.isDirectory();
            }

            @Override
            public String getDescription() {
                return "FUNCIONARIO (.funcionario)";
            }
        });
        abrir.setCurrentDirectory(new File("."));
        if (abrir.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
            File arquivo = abrir.getSelectedFile();
            nomearquivo = arquivo.getName();
            BufferedReader in = null;
            try {
                in = new BufferedReader(new FileReader(arquivo));
                while ((src = in.readLine()) != null) {
                    texto += src;
                }
                return texto;
            } catch (IOException ex) {
                Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
            }
        
        }
        return null;
    }

    public boolean save(String texto){
        try {
        JFileChooser janelasalvar = new JFileChooser();
        janelasalvar.setDialogTitle("salvar");
        janelasalvar.setCurrentDirectory(new File("."));
        if (janelasalvar.showSaveDialog(null) == JFileChooser.APPROVE_OPTION) {
            File arquivo = janelasalvar.getSelectedFile();
            try (PrintWriter pw = new PrintWriter(arquivo)) {
                pw.write(texto);
                pw.close();
            }
            return true;
        }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Visual.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }

}
